### ISSUE TITLE
Uncaught TypeError: this.setState is not a function

### ISSUE THREAD

**Issue by SolsWebdesign** [yireo-training/Yireo_ReactMinicart#4]
Hi, very nice module!
I have installed your extension (as well as the Yireo_React) and installed all the packages in the package.json through npm install. Then did a "gulp build" in the vendor/yireo/magento2-react-minicart/view/frontend directory. It compiles into a Minicart.js (as well as a CustomerData.js) which is then found in the compiled directory. 
After a static-content:deploy I get the compiled minicart in the theme and Magento finds it there.
The minicart works very nice, by the way, and I get a "The minicart is being toggled: 0.9161614346047424" message when I add something to cart. But I do get the following error(s):
Minicart.js? [sm]:17 Uncaught TypeError: this.setState is not a function
    at ko.subscription.callback (Minicart.js? [sm]:17)
   at Function.notifySubscribers (knockout.js:1330)
    at Function.valueHasMutated (knockout.js:1548)
    at Object.observable [as foobar] (knockout.js:1514)
and some more. 
I probably missed a step or did I do something not quite right?

**Comment by jissereitsma** [comment]
No, you did everything right. I used this repo many times for experiments and the toggling effect was a silly example. However, none of those experiments were solid and one of them (`foo`) caused a `this.setState` error which I never bothered to fix. I have now moved all experiments to another repo https://github.com/yireo-training/Yireo_ReactExample/ and cleaned up the ReactMinicart so that it is only doing what it is supposed to be doing: Replace the minicart.

Could you pull all changes, preferably wipe out all files (specifically your NPM lock-file and the `node_modules` folder) and retry? :)
